openapi: 3.0.3
info:
  title: ILRD Storage
  description: Describes the operations and schemas for ILRD Storage
  contact:
    email: adam.akiva@infinitylabs.co.il
  version: 0.0.0
servers:
  - url: http://localhost:9554/v0/api
tags:
  - name: general
paths:
  /health:
    get:
      servers:
        - url: http://localhost:9554
      tags:
        - general
      summary: Health check for the application
      description: Health check for the application
      responses:
        '204':
          description: The application is healthy
        '400':
          $ref: '#/components/responses/InvalidInputError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '504':
          $ref: '#/components/responses/GatewayTimeoutError'
    head:
      servers:
        - url: http://localhost:9554
      tags:
        - general
      summary: Health check for the application
      description: Health check for the application
      responses:
        '204':
          description: The application is healthy
        '400':
          $ref: '#/components/responses/InvalidInputError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '504':
          $ref: '#/components/responses/GatewayTimeoutError'
components:
  responses:
    InvalidInputError:
      description: Invalid input
    UnauthorizedError:
      description: Request without authentication
    ForbiddenError:
      description: >
        Request with valid authentication, but the token has no permissions
        for this type of request
    NotFoundError:
      description: The requested entity does not exist
    PayloadTooLargeError:
      description: The request size is too large
    ServerError:
      description: Server related error
    GatewayTimeoutError:
      description: >
        The server, while acting as a proxy did not receive a response in time